### ISSUE TITLE
不太明白 2）的意思

### ISSUE THREAD

**Issue by zanerogl** [fanchenxinok/glmark2_arm#1]
你好，我是一个新手，最近需要用rk3399来做项目，由于涉及到要安装glmark2，所以搜到了您的文章，以下是我的一些疑惑：
modify Makefile, then modify cross-comile tool gcc's env setting “CROSS_COMPILER”，modify USR_INC as your system root/usr/include
不明白使用交叉编译工具链，如果我直接在arm板子上编译的话要怎么修改？

**Comment by fanchenxinok** [comment]
来信已收到，谢谢！

**Comment by zanerogl** [comment]
你好，上面的问题已经解决，但是在编译好后运行glmark2报这个错误

rock@rockpi-4b:~/work/glmark2_arm-master$ sudo ./glmark2_arm 
Error: eglInitialize() failed with error: 0x3001
Error: eglInitialize() failed with error: 0x3001
Error: main: Could not initialize canvas

我的设备
CPU：rk3399
GPU：Mali T860
OS：Debian 10

**Comment by fanchenxinok** [comment]
那说明你的GPU不支持opengl, eglInitialize初始化失败说明没匹配的显卡。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchenxinok/glmark2_arm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 晚上8:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanchenxinok/glmark2_arm] 不太明白 2）的意思 (Issue #1)





 
你好，上面的问题已经解决，但是在编译好后运行glmark2报这个错误
 
***@***.***:~/work/glmark2_arm-master$ sudo ./glmark2_arm
 Error: eglInitialize() failed with error: 0x3001
 Error: eglInitialize() failed with error: 0x3001
 Error: main: Could not initialize canvas
 
我的设备
 CPU：rk3399
 GPU：Mali T860
 OS：Debian 10

**Comment by fanchenxinok** [comment]
来信已收到，谢谢！
